freeman:
  password:
    # shiro 加密算法
    algorithmName: md5
    # shiro 加密次数
    hashIterations: 2
  # JWT 过期时长, 单位:分钟
  jwtTimeOut: 1

server:
  port: 9081
  servlet:
    # 应用的访问路径
    # context-path: /
    session:
      # shiroConfig#sessionTime也是用的这个值 单位:分钟
      timeout: 60
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev #dev pro
  servlet:
    multipart:
      # 单个文件最大
      max-file-size: 100
      # 单次请求上传数据总大小
      max-request-size: 1000

#日志相关配置
logging:
  config: classpath:logback-spring.xml


management:
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


