
spring:
    #include: jdbc,brac
  aop:
    proxy-target-class: true
    auto: true
  #数据库配置
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://139.199.112.93:3307/freeman?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: lzx123
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://139.199.112.93:3307/freeman?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: lzx123
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://139.199.112.93:3307/freeman?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: lzx123
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

    #druid:
    #  stat-view-servlet:
    #    #以下4项，将来上生产环境以后一定要改！！！！！一定要改！！！！！一定要改！！！！！
    #    url-pattern: /druid/*
    #    allow: 127.0.0.1,*
    #    loginUsername: admin
    #    loginPassword: 123456
    #  initialSize: 5
    #  minIdle: 5
    #  maxActive: 20
    #  # 配置获取连接等待超时的时间
    #  maxWait: 60000
    #  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #  timeBetweenEvictionRunsMillis: 60000
    #  # 配置一个连接在池中最小生存的时间，单位是毫秒
    #  minEvictableIdleTimeMillis: 300000
    #  validationQuery: SELECT 1 FROM DUAL
    #  testWhileIdle: true
    #  testOnBorrow: false
    #  testOnReturn: false
    #  # 打开PSCache，并且指定每个连接上PSCache的大小
    #  poolPreparedStatements: true
    #  maxPoolPreparedStatementPerConnectionSize: 20
    #  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #  filters: stat,wall,slf4j
    #  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #  # 合并多个DruidDataSource的监控数据
    #  # useGlobalDataSourceStat: true
    #  #web-stat-filter.enabled: true
    #  #web-stat-filter.url-pattern: /*
    #  #web-stat-filter.exclusions: *.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
    #  #stat-view-servlet.deny: 192.168.1.73
    #  #stat-view-servlet.reset-enable: false

  jpa:
    # SpringBoot2.0以后需要指定方言才能使用InnoDB引擎
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    database: MYSQL
    # 显示后台处理的SQL语句
    showSql: true
    properties:
      hibernate:
        format_sql: false
    # 自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表
    hibernate:
      ddl-auto: none
    open-in-view: true

  redis:
    host: 139.199.112.93
    port: 6379
    password: lzx123
    timeout: 0
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000

#第三方配置
tools:
  #文件上传配置
  file:
    prefix-placeholder: #@@#
    prefix: http://xxx.xxx.com/files
    local:
      path: /home/images/files #tools.file.local.path
  #代码生成配置
  gen:
    #配置数据库名称
    dbname: freeman
    #默认生成路径
    default:
      #core模块的绝对路径
      genCoreBaseDir:
      #admin模块的绝对路径
      genAdminBaseDir:
      #api模块的绝对路径
      genApiBaseDir:


#flowable:
#  #关闭定时任务JOB
#  async-executor-activate: false
#  common:
#    app:
#      idm-url: /flowable/
#  rest:
#    app:
#      authentication-mode: verify-privilege
#  modeler:
#    app:
#      rest-enabled: true
#  database-schema-update: true